# Generated by Django 4.2.1 on 2023-07-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("text", models.TextField(blank=True, default="")),
                (
                    "letter_status",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "pending"), (1, "ready to send"), (2, "sent")],
                        default=0,
                    ),
                ),
            ],
            options={
                "ordering": ["-added_at"],
                "abstract": False,
            },
        ),
    ]
