# Generated by Django 4.2.1 on 2023-07-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="sended_at",
            field=models.DateField(blank=True, null=True),
        ),
    ]
