# Generated by Django 4.2.1 on 2023-06-01 21:10

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import src.timestamp.utils.base
import src.timestamp.utils.magic_valid_files


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=src.timestamp.utils.base.upload_img,
                        validators=[
                            src.timestamp.utils.magic_valid_files.validate_img_mimetype
                        ],
                        verbose_name="Avatar",
                    ),
                ),
                ("info", models.CharField(blank=True, default="", max_length=120)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProfileChart",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("profiles.profile",),
        ),
    ]
