# Generated by Django 4.2.1 on 2023-07-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="status",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Trialing"),
                    (2, "Active"),
                    (3, "Exempt"),
                    (4, "Cancelled"),
                    (5, "Trial Expired"),
                ],
                db_index=True,
                default=3,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="want_news",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
