# Generated by Django 4.2.1 on 2023-07-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_category_name_en_category_name_ru_category_name_uk"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="send_status",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "pend"), (1, "to send"), (2, "sent")],
                default=0,
            ),
        ),
    ]
