# Generated by Django 4.2.1 on 2023-07-28 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
        ("posts", "0003_post_send_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="letter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="contacts.newsletter",
            ),
        ),
    ]
