# Generated by Django 4.2.1 on 2023-08-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_trigger_en"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_en",
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_ru",
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_uk",
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
