# Generated by Django 4.2.1 on 2023-10-05 18:14

import django.db.models.deletion
from django.db import migrations, models

import src.posts.models.categ_model


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_add_unique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="categ",
            field=models.ForeignKey(
                default=src.posts.models.categ_model.Category.get_default_pk,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="posts",
                to="posts.category",
            ),
        ),
    ]
