# Generated by Django 4.2.1 on 2023-10-26 21:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0008_alter_relation_post_alter_relation_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="fans",
            field=models.ManyToManyField(
                related_name="post_fans",
                through="posts.Relation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
