# Generated by Django 4.2.1 on 2023-10-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0009_post_fans"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="count_bmarks",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
