# Generated by Django 4.2.1 on 2023-10-29 22:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0010_post_count_bmarks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relation",
            name="like",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="relation",
            unique_together={("user", "post")},
        ),
    ]
