# Generated by Django 4.2.1 on 2023-10-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0010_post_count_bmarks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="relation",
            name="like",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="relation",
            constraint=models.UniqueConstraint(
                fields=("user", "post"), name="unique_rels"
            ),
        ),
    ]
