# Generated by Django 4.2.1 on 2023-11-09 20:30

import embed_video.fields
from django.db import migrations, models

import src.core.utils.base


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0011_alter_relation_like_relation_unique_rels"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("url", embed_video.fields.EmbedVideoField()),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to=src.core.utils.base.upload_img
                    ),
                ),
                (
                    "categ",
                    models.IntegerField(
                        choices=[
                            (None, "(Unknown)"),
                            (0, "first"),
                            (1, "not_specified"),
                            (2, "endo"),
                            (3, "cardio"),
                            (4, "gastro"),
                            (5, "immune"),
                            (6, "uro_gen"),
                            (7, "neuro"),
                            (8, "toxic"),
                            (9, "old"),
                        ],
                        default=1,
                    ),
                ),
            ],
            options={
                "ordering": ["-added_at"],
                "abstract": False,
            },
        ),
    ]
