name: Tests Runner
on:
  - push
  - pull_request

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-22.04
    env:
      ALLOWED_HOSTS: "*"
      SECRET_KEY: "my big secret not seen"
      EMAIL_HOST: ${{vars.EMAIL_HOST}}
      EMAIL_HOST_USER: ${{vars.EMAIL_HOST_USER}}
      EMAIL_HOST_PASSWORD: ${{secrets.EMAIL_HOST_PASSWORD}}
      EMAIL_PORT: ${{vars.EMAIL_PORT}}
      EMAIL_BACKEND: ${{vars.EMAIL_BACKEND}}

    steps:
      - name: Get the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "reqs/*.txt"
      - name: Install OS packages
        run: sudo apt install python3-dev
      - name: Install Python packages
        run: pip install -r reqs/reqlinux.txt -r reqs/dev.txt

      - name: Test it
        run: python manage.py test
